// This file is generated by cpp/generate_glue_prototype.js
// Do not edit this file directly

import type { GlueMessageProto } from './glue';

export const GLUE_VERSION = 3;

export const GLUE_MESSAGE_PROTOTYPES: { [name: string]: GlueMessageProto } = {
  "erro_evt": {
    "name": "erro_evt",
    "structName": "glue_msg_error",
    "className": "GlueMsgError",
    "fields": [
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "load_req": {
    "name": "load_req",
    "structName": "glue_msg_load_req",
    "className": "GlueMsgLoadReq",
    "fields": [
      {
        "type": "arr_str",
        "name": "model_paths",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "n_ctx_auto",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_mmap",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_mlock",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_webgpu",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_gpu_layers",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "no_perf",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "seed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_threads",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "embeddings",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "offload_kqv",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_batch",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_seq_max",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "pooling_type",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "rope_scaling_type",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "rope_freq_base",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "rope_freq_scale",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_ext_factor",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_attn_factor",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_beta_fast",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_beta_slow",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "yarn_orig_ctx",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "cache_type_k",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "cache_type_v",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "flash_attn",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "swa_full",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "kv_unified",
        "isNullable": true
      }
    ]
  },
  "load_res": {
    "name": "load_res",
    "structName": "glue_msg_load_res",
    "className": "GlueMsgLoadRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_batch",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ubatch",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_vocab",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx_train",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_embd",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_layer",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "metadata_key",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "metadata_val",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_bos",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_eos",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_eot",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "list_tokens_eog",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "add_bos_token",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "add_eos_token",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "has_encoder",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_decoder_start",
        "isNullable": false
      }
    ]
  },
  "opti_req": {
    "name": "opti_req",
    "structName": "glue_msg_set_options_req",
    "className": "GlueMsgSetOptionsReq",
    "fields": [
      {
        "type": "bool",
        "name": "embeddings",
        "isNullable": false
      }
    ]
  },
  "opti_res": {
    "name": "opti_res",
    "structName": "glue_msg_set_options_res",
    "className": "GlueMsgSetOptionsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "sint_req": {
    "name": "sint_req",
    "structName": "glue_msg_sampling_init_req",
    "className": "GlueMsgSamplingInitReq",
    "fields": [
      {
        "type": "int",
        "name": "mirostat",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "mirostat_tau",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "mirostat_eta",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "temp",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "top_p",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "top_k",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "penalty_last_n",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_repeat",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_freq",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_present",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "dynatemp_range",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "dynatemp_exponent",
        "isNullable": true
      },
      {
        "type": "arr_str",
        "name": "samplers_sequence",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "grammar",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_prev",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_probs",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "min_p",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "typical_p",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "typ_p",
        "isNullable": true
      },
      {
        "type": "arr_int",
        "name": "logit_bias_toks",
        "isNullable": true
      },
      {
        "type": "arr_float",
        "name": "logit_bias_vals",
        "isNullable": true
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": true
      }
    ]
  },
  "sint_res": {
    "name": "sint_res",
    "structName": "glue_msg_sampling_init_res",
    "className": "GlueMsgSamplingInitRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "gvoc_req": {
    "name": "gvoc_req",
    "structName": "glue_msg_get_vocab_req",
    "className": "GlueMsgGetVocabReq",
    "fields": []
  },
  "gvoc_res": {
    "name": "gvoc_res",
    "structName": "glue_msg_get_vocab_res",
    "className": "GlueMsgGetVocabRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_raw",
        "name": "vocab",
        "isNullable": false
      }
    ]
  },
  "lkup_req": {
    "name": "lkup_req",
    "structName": "glue_msg_lookup_token_req",
    "className": "GlueMsgLookupTokenReq",
    "fields": [
      {
        "type": "str",
        "name": "piece",
        "isNullable": false
      }
    ]
  },
  "lkup_res": {
    "name": "lkup_res",
    "structName": "glue_msg_lookup_token_res",
    "className": "GlueMsgLookupTokenRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token",
        "isNullable": false
      }
    ]
  },
  "tokn_req": {
    "name": "tokn_req",
    "structName": "glue_msg_tokenize_req",
    "className": "GlueMsgTokenizeReq",
    "fields": [
      {
        "type": "str",
        "name": "text",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "special",
        "isNullable": false
      }
    ]
  },
  "tokn_res": {
    "name": "tokn_res",
    "structName": "glue_msg_tokenize_res",
    "className": "GlueMsgTokenizeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "dtkn_req": {
    "name": "dtkn_req",
    "structName": "glue_msg_detokenize_req",
    "className": "GlueMsgDetokenizeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "dtkn_res": {
    "name": "dtkn_res",
    "structName": "glue_msg_detokenize_res",
    "className": "GlueMsgDetokenizeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "raw",
        "name": "buffer",
        "isNullable": false
      }
    ]
  },
  "deco_req": {
    "name": "deco_req",
    "structName": "glue_msg_decode_req",
    "className": "GlueMsgDecodeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "skip_logits",
        "isNullable": false
      }
    ]
  },
  "deco_res": {
    "name": "deco_res",
    "structName": "glue_msg_decode_res",
    "className": "GlueMsgDecodeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "enco_req": {
    "name": "enco_req",
    "structName": "glue_msg_encode_req",
    "className": "GlueMsgEncodeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "enco_res": {
    "name": "enco_res",
    "structName": "glue_msg_encode_res",
    "className": "GlueMsgEncodeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "ssam_req": {
    "name": "ssam_req",
    "structName": "glue_msg_sampling_sample_req",
    "className": "GlueMsgSamplingSampleReq",
    "fields": []
  },
  "ssam_res": {
    "name": "ssam_res",
    "structName": "glue_msg_sampling_sample_res",
    "className": "GlueMsgSamplingSampleRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "raw",
        "name": "piece",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token",
        "isNullable": false
      }
    ]
  },
  "sacc_req": {
    "name": "sacc_req",
    "structName": "glue_msg_sampling_accept_req",
    "className": "GlueMsgSamplingAcceptReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sacc_res": {
    "name": "sacc_res",
    "structName": "glue_msg_sampling_accept_res",
    "className": "GlueMsgSamplingAcceptRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "glog_req": {
    "name": "glog_req",
    "structName": "glue_msg_get_logits_req",
    "className": "GlueMsgGetLogitsReq",
    "fields": [
      {
        "type": "int",
        "name": "top_k",
        "isNullable": false
      }
    ]
  },
  "glog_res": {
    "name": "glog_res",
    "structName": "glue_msg_get_logits_res",
    "className": "GlueMsgGetLogitsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      },
      {
        "type": "arr_float",
        "name": "probs",
        "isNullable": false
      }
    ]
  },
  "gemb_req": {
    "name": "gemb_req",
    "structName": "glue_msg_get_embeddings_req",
    "className": "GlueMsgGetEmbeddingsReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "gemb_res": {
    "name": "gemb_res",
    "structName": "glue_msg_get_embeddings_res",
    "className": "GlueMsgGetEmbeddingsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "arr_float",
        "name": "embeddings",
        "isNullable": false
      }
    ]
  },
  "kvcr_req": {
    "name": "kvcr_req",
    "structName": "glue_msg_get_kv_remove_req",
    "className": "GlueMsgGetKvRemoveReq",
    "fields": [
      {
        "type": "int",
        "name": "n_keep",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_discard",
        "isNullable": false
      }
    ]
  },
  "kvcr_res": {
    "name": "kvcr_res",
    "structName": "glue_msg_get_kv_remove_res",
    "className": "GlueMsgGetKvRemoveRes",
    "fields": [
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "kvcc_req": {
    "name": "kvcc_req",
    "structName": "glue_msg_get_kv_clear_req",
    "className": "GlueMsgGetKvClearReq",
    "fields": []
  },
  "kvcc_res": {
    "name": "kvcc_res",
    "structName": "glue_msg_get_kv_clear_res",
    "className": "GlueMsgGetKvClearRes",
    "fields": [
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "sesa_req": {
    "name": "sesa_req",
    "structName": "glue_msg_session_save_req",
    "className": "GlueMsgSessionSaveReq",
    "fields": [
      {
        "type": "str",
        "name": "session_path",
        "isNullable": false
      }
    ]
  },
  "sesa_res": {
    "name": "sesa_res",
    "structName": "glue_msg_session_save_res",
    "className": "GlueMsgSessionSaveRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sesl_req": {
    "name": "sesl_req",
    "structName": "glue_msg_session_load_req",
    "className": "GlueMsgSessionLoadReq",
    "fields": [
      {
        "type": "str",
        "name": "session_path",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sesl_res": {
    "name": "sesl_res",
    "structName": "glue_msg_session_load_res",
    "className": "GlueMsgSessionLoadRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "stat_req": {
    "name": "stat_req",
    "structName": "glue_msg_status_req",
    "className": "GlueMsgStatusReq",
    "fields": []
  },
  "stat_res": {
    "name": "stat_res",
    "structName": "glue_msg_status_res",
    "className": "GlueMsgStatusRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "pctx_req": {
    "name": "pctx_req",
    "structName": "glue_msg_perf_context_req",
    "className": "GlueMsgPerfContextReq",
    "fields": []
  },
  "pctx_res": {
    "name": "pctx_res",
    "structName": "glue_msg_perf_context_res",
    "className": "GlueMsgPerfContextRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_start_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_load_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_p_eval_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_eval_ms",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_p_eval",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_eval",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_reused",
        "isNullable": false
      }
    ]
  },
  "prst_req": {
    "name": "prst_req",
    "structName": "glue_msg_perf_reset_req",
    "className": "GlueMsgPerfResetReq",
    "fields": []
  },
  "prst_res": {
    "name": "prst_res",
    "structName": "glue_msg_perf_reset_res",
    "className": "GlueMsgPerfResetRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "tben_req": {
    "name": "tben_req",
    "structName": "glue_msg_test_benchmark_req",
    "className": "GlueMsgTestBenchmarkReq",
    "fields": [
      {
        "type": "str",
        "name": "type",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_samples",
        "isNullable": false
      }
    ]
  },
  "tben_res": {
    "name": "tben_res",
    "structName": "glue_msg_test_benchmark_res",
    "className": "GlueMsgTestBenchmarkRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "t_ms",
        "isNullable": false
      }
    ]
  },
  "tper_req": {
    "name": "tper_req",
    "structName": "glue_msg_test_perplexity_req",
    "className": "GlueMsgTestPerplexityReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "tper_res": {
    "name": "tper_res",
    "structName": "glue_msg_test_perplexity_res",
    "className": "GlueMsgTestPerplexityRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "ppl",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "nll",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "cross_entropy",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "t_ms",
        "isNullable": false
      }
    ]
  },
  "cfmt_req": {
    "name": "cfmt_req",
    "structName": "glue_msg_chat_format_req",
    "className": "GlueMsgChatFormatReq",
    "fields": [
      {
        "type": "str",
        "name": "tmpl",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "add_ass",
        "isNullable": true
      },
      {
        "type": "arr_str",
        "name": "roles",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "contents",
        "isNullable": false
      }
    ]
  },
  "cfmt_res": {
    "name": "cfmt_res",
    "structName": "glue_msg_chat_format_res",
    "className": "GlueMsgChatFormatRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "formatted_chat",
        "isNullable": false
      }
    ]
  },
  "kvss_req": {
    "name": "kvss_req",
    "structName": "glue_msg_kv_seq_save_req",
    "className": "GlueMsgKvSeqSaveReq",
    "fields": [
      {
        "type": "int",
        "name": "slot_id",
        "isNullable": false
      }
    ]
  },
  "kvss_res": {
    "name": "kvss_res",
    "structName": "glue_msg_kv_seq_save_res",
    "className": "GlueMsgKvSeqSaveRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "kvsr_req": {
    "name": "kvsr_req",
    "structName": "glue_msg_kv_seq_restore_req",
    "className": "GlueMsgKvSeqRestoreReq",
    "fields": [
      {
        "type": "int",
        "name": "slot_id",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "kvsr_res": {
    "name": "kvsr_res",
    "structName": "glue_msg_kv_seq_restore_res",
    "className": "GlueMsgKvSeqRestoreRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "kvsm_req": {
    "name": "kvsm_req",
    "structName": "glue_msg_kv_seq_rm_req",
    "className": "GlueMsgKvSeqRmReq",
    "fields": [
      {
        "type": "int",
        "name": "slot_id",
        "isNullable": false
      }
    ]
  },
  "kvsm_res": {
    "name": "kvsm_res",
    "structName": "glue_msg_kv_seq_rm_res",
    "className": "GlueMsgKvSeqRmRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "trin_req": {
    "name": "trin_req",
    "structName": "glue_msg_tree_init_req",
    "className": "GlueMsgTreeInitReq",
    "fields": [
      {
        "type": "int",
        "name": "memory_cap_bytes",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "tiered_cache_enabled",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l1_token_cap",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l2_token_cap",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l3_token_cap",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_prune_l1_l2_token_threshold",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_prune_l2_l3_token_threshold",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "tier_l3_path",
        "isNullable": false
      }
    ]
  },
  "trin_res": {
    "name": "trin_res",
    "structName": "glue_msg_tree_init_res",
    "className": "GlueMsgTreeInitRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "trst_req": {
    "name": "trst_req",
    "structName": "glue_msg_tree_state_req",
    "className": "GlueMsgTreeStateReq",
    "fields": []
  },
  "trst_res": {
    "name": "trst_res",
    "structName": "glue_msg_tree_state_res",
    "className": "GlueMsgTreeStateRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "ids",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "parent_ids",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "user_texts",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "assistant_texts",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "statuses",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "prefix_token_counts",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "generation_time_ms",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "cached_token_counts",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "snapshot_token_bytes",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "created_at_s",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "last_accessed_at_s",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "child_offsets",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "child_ids",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "root_id",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "active_node_id",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "next_id",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "context_memory_bytes",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "memory_cap_bytes",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "total_snapshot_token_bytes",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "last_pruned_node_ids",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "last_pruned_at_s",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "tiered_cache_enabled",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l1_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l2_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l3_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l1_slots",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l2_slots",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l3_slots",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_promotions",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_demotions",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_disk_reads",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_disk_writes",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "tier_l3_overflow_events",
        "isNullable": false
      }
    ]
  },
  "trsw_req": {
    "name": "trsw_req",
    "structName": "glue_msg_tree_switch_req",
    "className": "GlueMsgTreeSwitchReq",
    "fields": [
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      }
    ]
  },
  "trsw_res": {
    "name": "trsw_res",
    "structName": "glue_msg_tree_switch_res",
    "className": "GlueMsgTreeSwitchRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "trpr_req": {
    "name": "trpr_req",
    "structName": "glue_msg_tree_prepare_turn_req",
    "className": "GlueMsgTreePrepareTurnReq",
    "fields": [
      {
        "type": "int",
        "name": "parent_id",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "user_text",
        "isNullable": false
      }
    ]
  },
  "trpr_res": {
    "name": "trpr_res",
    "structName": "glue_msg_tree_prepare_turn_res",
    "className": "GlueMsgTreePrepareTurnRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      }
    ]
  },
  "trfn_req": {
    "name": "trfn_req",
    "structName": "glue_msg_tree_finish_turn_req",
    "className": "GlueMsgTreeFinishTurnReq",
    "fields": [
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "assistant_text",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "generation_time_ms",
        "isNullable": false
      }
    ]
  },
  "trfn_res": {
    "name": "trfn_res",
    "structName": "glue_msg_tree_finish_turn_res",
    "className": "GlueMsgTreeFinishTurnRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "trde_req": {
    "name": "trde_req",
    "structName": "glue_msg_tree_delete_req",
    "className": "GlueMsgTreeDeleteReq",
    "fields": [
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      }
    ]
  },
  "trde_res": {
    "name": "trde_res",
    "structName": "glue_msg_tree_delete_res",
    "className": "GlueMsgTreeDeleteRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "trrs_req": {
    "name": "trrs_req",
    "structName": "glue_msg_tree_reset_req",
    "className": "GlueMsgTreeResetReq",
    "fields": []
  },
  "trrs_res": {
    "name": "trrs_res",
    "structName": "glue_msg_tree_reset_res",
    "className": "GlueMsgTreeResetRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "tchs_req": {
    "name": "tchs_req",
    "structName": "glue_msg_tree_chat_start_req",
    "className": "GlueMsgTreeChatStartReq",
    "fields": [
      {
        "type": "int",
        "name": "parent_id",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "user_text",
        "isNullable": false
      }
    ]
  },
  "tchs_res": {
    "name": "tchs_res",
    "structName": "glue_msg_tree_chat_start_res",
    "className": "GlueMsgTreeChatStartRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "roles",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "contents",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "formatted_chat",
        "isNullable": false
      }
    ]
  },
  "tchf_req": {
    "name": "tchf_req",
    "structName": "glue_msg_tree_chat_finish_req",
    "className": "GlueMsgTreeChatFinishReq",
    "fields": [
      {
        "type": "int",
        "name": "node_id",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "assistant_text",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "generation_time_ms",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "aborted_or_error",
        "isNullable": false
      }
    ]
  },
  "tchf_res": {
    "name": "tchf_res",
    "structName": "glue_msg_tree_chat_finish_res",
    "className": "GlueMsgTreeChatFinishRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  }
};

// struct glue_msg_error
export interface GlueMsgError {
  _name: "erro_evt";
  message: string;
}

// struct glue_msg_load_req
export interface GlueMsgLoadReq {
  _name: "load_req";
  model_paths: string[];
  n_ctx_auto: boolean;
  use_mmap: boolean;
  use_mlock: boolean;
  use_webgpu: boolean;
  n_gpu_layers: number;
  no_perf: boolean;
  seed: number;
  n_ctx: number;
  n_threads: number;
  embeddings?: boolean | undefined;
  offload_kqv?: boolean | undefined;
  n_batch?: number | undefined;
  n_seq_max?: number | undefined;
  pooling_type?: string | undefined;
  rope_scaling_type?: string | undefined;
  rope_freq_base?: number | undefined;
  rope_freq_scale?: number | undefined;
  yarn_ext_factor?: number | undefined;
  yarn_attn_factor?: number | undefined;
  yarn_beta_fast?: number | undefined;
  yarn_beta_slow?: number | undefined;
  yarn_orig_ctx?: number | undefined;
  cache_type_k?: string | undefined;
  cache_type_v?: string | undefined;
  flash_attn?: boolean | undefined;
  swa_full?: boolean | undefined;
  kv_unified?: boolean | undefined;
}

// struct glue_msg_load_res
export interface GlueMsgLoadRes {
  _name: "load_res";
  success: boolean;
  n_ctx: number;
  n_batch: number;
  n_ubatch: number;
  n_vocab: number;
  n_ctx_train: number;
  n_embd: number;
  n_layer: number;
  metadata_key: string[];
  metadata_val: string[];
  token_bos: number;
  token_eos: number;
  token_eot: number;
  list_tokens_eog: number[];
  add_bos_token: boolean;
  add_eos_token: boolean;
  has_encoder: boolean;
  token_decoder_start: number;
}

// struct glue_msg_set_options_req
export interface GlueMsgSetOptionsReq {
  _name: "opti_req";
  embeddings: boolean;
}

// struct glue_msg_set_options_res
export interface GlueMsgSetOptionsRes {
  _name: "opti_res";
  success: boolean;
}

// struct glue_msg_sampling_init_req
export interface GlueMsgSamplingInitReq {
  _name: "sint_req";
  mirostat?: number | undefined;
  mirostat_tau?: number | undefined;
  mirostat_eta?: number | undefined;
  temp?: number | undefined;
  top_p?: number | undefined;
  top_k?: number | undefined;
  penalty_last_n?: number | undefined;
  penalty_repeat?: number | undefined;
  penalty_freq?: number | undefined;
  penalty_present?: number | undefined;
  dynatemp_range?: number | undefined;
  dynatemp_exponent?: number | undefined;
  samplers_sequence?: string[] | undefined;
  grammar?: string | undefined;
  n_prev?: number | undefined;
  n_probs?: number | undefined;
  min_p?: number | undefined;
  typical_p?: number | undefined;
  typ_p?: number | undefined;
  logit_bias_toks?: number[] | undefined;
  logit_bias_vals?: number[] | undefined;
  tokens?: number[] | undefined;
}

// struct glue_msg_sampling_init_res
export interface GlueMsgSamplingInitRes {
  _name: "sint_res";
  success: boolean;
}

// struct glue_msg_get_vocab_req
export interface GlueMsgGetVocabReq {
  _name: "gvoc_req";
}

// struct glue_msg_get_vocab_res
export interface GlueMsgGetVocabRes {
  _name: "gvoc_res";
  success: boolean;
  vocab: Uint8Array[];
}

// struct glue_msg_lookup_token_req
export interface GlueMsgLookupTokenReq {
  _name: "lkup_req";
  piece: string;
}

// struct glue_msg_lookup_token_res
export interface GlueMsgLookupTokenRes {
  _name: "lkup_res";
  success: boolean;
  token: number;
}

// struct glue_msg_tokenize_req
export interface GlueMsgTokenizeReq {
  _name: "tokn_req";
  text: string;
  special: boolean;
}

// struct glue_msg_tokenize_res
export interface GlueMsgTokenizeRes {
  _name: "tokn_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_detokenize_req
export interface GlueMsgDetokenizeReq {
  _name: "dtkn_req";
  tokens: number[];
}

// struct glue_msg_detokenize_res
export interface GlueMsgDetokenizeRes {
  _name: "dtkn_res";
  success: boolean;
  buffer: Uint8Array;
}

// struct glue_msg_decode_req
export interface GlueMsgDecodeReq {
  _name: "deco_req";
  tokens: number[];
  skip_logits: boolean;
}

// struct glue_msg_decode_res
export interface GlueMsgDecodeRes {
  _name: "deco_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_encode_req
export interface GlueMsgEncodeReq {
  _name: "enco_req";
  tokens: number[];
}

// struct glue_msg_encode_res
export interface GlueMsgEncodeRes {
  _name: "enco_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_sampling_sample_req
export interface GlueMsgSamplingSampleReq {
  _name: "ssam_req";
}

// struct glue_msg_sampling_sample_res
export interface GlueMsgSamplingSampleRes {
  _name: "ssam_res";
  success: boolean;
  piece: Uint8Array;
  token: number;
}

// struct glue_msg_sampling_accept_req
export interface GlueMsgSamplingAcceptReq {
  _name: "sacc_req";
  tokens: number[];
}

// struct glue_msg_sampling_accept_res
export interface GlueMsgSamplingAcceptRes {
  _name: "sacc_res";
  success: boolean;
}

// struct glue_msg_get_logits_req
export interface GlueMsgGetLogitsReq {
  _name: "glog_req";
  top_k: number;
}

// struct glue_msg_get_logits_res
export interface GlueMsgGetLogitsRes {
  _name: "glog_res";
  success: boolean;
  tokens: number[];
  probs: number[];
}

// struct glue_msg_get_embeddings_req
export interface GlueMsgGetEmbeddingsReq {
  _name: "gemb_req";
  tokens: number[];
}

// struct glue_msg_get_embeddings_res
export interface GlueMsgGetEmbeddingsRes {
  _name: "gemb_res";
  success: boolean;
  message: string;
  embeddings: number[];
}

// struct glue_msg_get_kv_remove_req
export interface GlueMsgGetKvRemoveReq {
  _name: "kvcr_req";
  n_keep: number;
  n_discard: number;
}

// struct glue_msg_get_kv_remove_res
export interface GlueMsgGetKvRemoveRes {
  _name: "kvcr_res";
  n_past: number;
  success: boolean;
}

// struct glue_msg_get_kv_clear_req
export interface GlueMsgGetKvClearReq {
  _name: "kvcc_req";
}

// struct glue_msg_get_kv_clear_res
export interface GlueMsgGetKvClearRes {
  _name: "kvcc_res";
  n_past: number;
  success: boolean;
}

// struct glue_msg_session_save_req
export interface GlueMsgSessionSaveReq {
  _name: "sesa_req";
  session_path: string;
}

// struct glue_msg_session_save_res
export interface GlueMsgSessionSaveRes {
  _name: "sesa_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_session_load_req
export interface GlueMsgSessionLoadReq {
  _name: "sesl_req";
  session_path: string;
  tokens: number[];
}

// struct glue_msg_session_load_res
export interface GlueMsgSessionLoadRes {
  _name: "sesl_res";
  success: boolean;
}

// struct glue_msg_status_req
export interface GlueMsgStatusReq {
  _name: "stat_req";
}

// struct glue_msg_status_res
export interface GlueMsgStatusRes {
  _name: "stat_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_perf_context_req
export interface GlueMsgPerfContextReq {
  _name: "pctx_req";
}

// struct glue_msg_perf_context_res
export interface GlueMsgPerfContextRes {
  _name: "pctx_res";
  success: boolean;
  t_start_ms: number;
  t_load_ms: number;
  t_p_eval_ms: number;
  t_eval_ms: number;
  n_p_eval: number;
  n_eval: number;
  n_reused: number;
}

// struct glue_msg_perf_reset_req
export interface GlueMsgPerfResetReq {
  _name: "prst_req";
}

// struct glue_msg_perf_reset_res
export interface GlueMsgPerfResetRes {
  _name: "prst_res";
  success: boolean;
}

// struct glue_msg_test_benchmark_req
export interface GlueMsgTestBenchmarkReq {
  _name: "tben_req";
  type: string;
  n_samples: number;
}

// struct glue_msg_test_benchmark_res
export interface GlueMsgTestBenchmarkRes {
  _name: "tben_res";
  success: boolean;
  message: string;
  t_ms: number;
}

// struct glue_msg_test_perplexity_req
export interface GlueMsgTestPerplexityReq {
  _name: "tper_req";
  tokens: number[];
}

// struct glue_msg_test_perplexity_res
export interface GlueMsgTestPerplexityRes {
  _name: "tper_res";
  success: boolean;
  message: string;
  ppl: number;
  nll: number;
  cross_entropy: number;
  n_tokens: number;
  t_ms: number;
}

// struct glue_msg_chat_format_req
export interface GlueMsgChatFormatReq {
  _name: "cfmt_req";
  tmpl?: string | undefined;
  add_ass?: boolean | undefined;
  roles: string[];
  contents: string[];
}

// struct glue_msg_chat_format_res
export interface GlueMsgChatFormatRes {
  _name: "cfmt_res";
  success: boolean;
  message: string;
  formatted_chat: string;
}

// struct glue_msg_kv_seq_save_req
export interface GlueMsgKvSeqSaveReq {
  _name: "kvss_req";
  slot_id: number;
}

// struct glue_msg_kv_seq_save_res
export interface GlueMsgKvSeqSaveRes {
  _name: "kvss_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_kv_seq_restore_req
export interface GlueMsgKvSeqRestoreReq {
  _name: "kvsr_req";
  slot_id: number;
  n_past: number;
}

// struct glue_msg_kv_seq_restore_res
export interface GlueMsgKvSeqRestoreRes {
  _name: "kvsr_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_kv_seq_rm_req
export interface GlueMsgKvSeqRmReq {
  _name: "kvsm_req";
  slot_id: number;
}

// struct glue_msg_kv_seq_rm_res
export interface GlueMsgKvSeqRmRes {
  _name: "kvsm_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_init_req
export interface GlueMsgTreeInitReq {
  _name: "trin_req";
  memory_cap_bytes: number;
  tiered_cache_enabled: boolean;
  tier_l1_token_cap: number;
  tier_l2_token_cap: number;
  tier_l3_token_cap: number;
  tier_prune_l1_l2_token_threshold: number;
  tier_prune_l2_l3_token_threshold: number;
  tier_l3_path: string;
}

// struct glue_msg_tree_init_res
export interface GlueMsgTreeInitRes {
  _name: "trin_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_state_req
export interface GlueMsgTreeStateReq {
  _name: "trst_req";
}

// struct glue_msg_tree_state_res
export interface GlueMsgTreeStateRes {
  _name: "trst_res";
  success: boolean;
  message: string;
  ids: number[];
  parent_ids: number[];
  user_texts: string[];
  assistant_texts: string[];
  statuses: string[];
  prefix_token_counts: number[];
  generation_time_ms: number[];
  cached_token_counts: number[];
  snapshot_token_bytes: number[];
  created_at_s: number[];
  last_accessed_at_s: number[];
  child_offsets: number[];
  child_ids: number[];
  root_id: number;
  active_node_id: number;
  next_id: number;
  context_memory_bytes: number;
  memory_cap_bytes: number;
  total_snapshot_token_bytes: number;
  last_pruned_node_ids: number[];
  last_pruned_at_s: number;
  tiered_cache_enabled: boolean;
  tier_l1_tokens: number;
  tier_l2_tokens: number;
  tier_l3_tokens: number;
  tier_l1_slots: number;
  tier_l2_slots: number;
  tier_l3_slots: number;
  tier_promotions: number;
  tier_demotions: number;
  tier_disk_reads: number;
  tier_disk_writes: number;
  tier_l3_overflow_events: number;
}

// struct glue_msg_tree_switch_req
export interface GlueMsgTreeSwitchReq {
  _name: "trsw_req";
  node_id: number;
}

// struct glue_msg_tree_switch_res
export interface GlueMsgTreeSwitchRes {
  _name: "trsw_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_prepare_turn_req
export interface GlueMsgTreePrepareTurnReq {
  _name: "trpr_req";
  parent_id: number;
  user_text: string;
}

// struct glue_msg_tree_prepare_turn_res
export interface GlueMsgTreePrepareTurnRes {
  _name: "trpr_res";
  success: boolean;
  message: string;
  node_id: number;
}

// struct glue_msg_tree_finish_turn_req
export interface GlueMsgTreeFinishTurnReq {
  _name: "trfn_req";
  node_id: number;
  assistant_text: string;
  generation_time_ms: number;
}

// struct glue_msg_tree_finish_turn_res
export interface GlueMsgTreeFinishTurnRes {
  _name: "trfn_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_delete_req
export interface GlueMsgTreeDeleteReq {
  _name: "trde_req";
  node_id: number;
}

// struct glue_msg_tree_delete_res
export interface GlueMsgTreeDeleteRes {
  _name: "trde_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_reset_req
export interface GlueMsgTreeResetReq {
  _name: "trrs_req";
}

// struct glue_msg_tree_reset_res
export interface GlueMsgTreeResetRes {
  _name: "trrs_res";
  success: boolean;
  message: string;
}

// struct glue_msg_tree_chat_start_req
export interface GlueMsgTreeChatStartReq {
  _name: "tchs_req";
  parent_id: number;
  user_text: string;
}

// struct glue_msg_tree_chat_start_res
export interface GlueMsgTreeChatStartRes {
  _name: "tchs_res";
  success: boolean;
  message: string;
  node_id: number;
  roles: string[];
  contents: string[];
  formatted_chat: string;
}

// struct glue_msg_tree_chat_finish_req
export interface GlueMsgTreeChatFinishReq {
  _name: "tchf_req";
  node_id: number;
  assistant_text: string;
  generation_time_ms: number;
  aborted_or_error: boolean;
}

// struct glue_msg_tree_chat_finish_res
export interface GlueMsgTreeChatFinishRes {
  _name: "tchf_res";
  success: boolean;
  message: string;
}


export type GlueMsg = GlueMsgError | GlueMsgLoadReq | GlueMsgLoadRes | GlueMsgSetOptionsReq | GlueMsgSetOptionsRes | GlueMsgSamplingInitReq | GlueMsgSamplingInitRes | GlueMsgGetVocabReq | GlueMsgGetVocabRes | GlueMsgLookupTokenReq | GlueMsgLookupTokenRes | GlueMsgTokenizeReq | GlueMsgTokenizeRes | GlueMsgDetokenizeReq | GlueMsgDetokenizeRes | GlueMsgDecodeReq | GlueMsgDecodeRes | GlueMsgEncodeReq | GlueMsgEncodeRes | GlueMsgSamplingSampleReq | GlueMsgSamplingSampleRes | GlueMsgSamplingAcceptReq | GlueMsgSamplingAcceptRes | GlueMsgGetLogitsReq | GlueMsgGetLogitsRes | GlueMsgGetEmbeddingsReq | GlueMsgGetEmbeddingsRes | GlueMsgGetKvRemoveReq | GlueMsgGetKvRemoveRes | GlueMsgGetKvClearReq | GlueMsgGetKvClearRes | GlueMsgSessionSaveReq | GlueMsgSessionSaveRes | GlueMsgSessionLoadReq | GlueMsgSessionLoadRes | GlueMsgStatusReq | GlueMsgStatusRes | GlueMsgPerfContextReq | GlueMsgPerfContextRes | GlueMsgPerfResetReq | GlueMsgPerfResetRes | GlueMsgTestBenchmarkReq | GlueMsgTestBenchmarkRes | GlueMsgTestPerplexityReq | GlueMsgTestPerplexityRes | GlueMsgChatFormatReq | GlueMsgChatFormatRes | GlueMsgKvSeqSaveReq | GlueMsgKvSeqSaveRes | GlueMsgKvSeqRestoreReq | GlueMsgKvSeqRestoreRes | GlueMsgKvSeqRmReq | GlueMsgKvSeqRmRes | GlueMsgTreeInitReq | GlueMsgTreeInitRes | GlueMsgTreeStateReq | GlueMsgTreeStateRes | GlueMsgTreeSwitchReq | GlueMsgTreeSwitchRes | GlueMsgTreePrepareTurnReq | GlueMsgTreePrepareTurnRes | GlueMsgTreeFinishTurnReq | GlueMsgTreeFinishTurnRes | GlueMsgTreeDeleteReq | GlueMsgTreeDeleteRes | GlueMsgTreeResetReq | GlueMsgTreeResetRes | GlueMsgTreeChatStartReq | GlueMsgTreeChatStartRes | GlueMsgTreeChatFinishReq | GlueMsgTreeChatFinishRes;
